apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbdpl-mg
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: dbpod-mg
        image: <insert-db-image>
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "passwors"