apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apprepset-mg
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: apppod-mg
        image: <insert-app-image>
        ports:
        - containerPort: 8080
        env:
          - name: DBUSER
            value: "root"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            value: "wordpass"
          - name: APP_COLOR
            value: "blue"
          - name: DBHOST
            value: "10.244.0.5"
          - name: DBPORT
            value: "3306"