apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dbrepset-mg
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: dbpod-mg
        image: 179267739179.dkr.ecr.us-east-1.amazonaws.com/mgibson13-asgn2-repository:my_db
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "passwors"