apiVersion: v1
kind: Pod
metadata:
  name: apppod-mg
spec:
  containers:
    - name: apppod-mg
      image: <insert-apppod-link>
      ports:
        - containerPort: 8080
      env:
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "wordpass"
        - name: APP_COLOR
          value: "blue"
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBPORT
          value: "3306"