apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  containers:
    - name: mysql
      image: <insert-dbpod-image>
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"