apiVersion: v1
kind: Pod
metadata:
  name: dbpod-mg
spec:
  containers:
    - name: mysql
      image: 179267739179.dkr.ecr.us-east-1.amazonaws.com/mgibson13-asgn2-repository:my_db
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"